Repository EFForg/privacybadger, pull requests merged in 2018-04, with the labels that each got.

#1938 MDFP for TechMedia sites
  src/js/multiDomainFirstParties.js
Labels: MDFP

#1934 Add Salesforce domains to MDFP
  src/js/multiDomainFirstParties.js
Labels: MDFP

#1940 Update Chinese translation
  src/_locales/zh/messages.json
Labels: translations

#1943 Propose fix a typo
  doc/DESIGN-AND-ROADMAP.md
Labels: bug, documentation & specs

#1936 Add openload.co to yellowlist
  src/data/yellowlist.txt
Labels: yellowlist

#1941 Fix DNT checking in Private Browsing/Incognito
  src/js/webrequest.js
Labels: DNT policy

#1942 Add libsyn.com to yellowlist
  src/data/yellowlist.txt
Labels: yellowlist

#1957 Add ocdn.eu to yellowlist
  src/data/yellowlist.txt
Labels: yellowlist

#1959 Add rewardstyle.com to yellowlist
  src/data/yellowlist.txt
Labels: yellowlist

#1960 Add marketo.com to yellowlist
  src/data/yellowlist.txt
Labels: yellowlist

#1964 Updated Czech (cs_CZ) translation
  src/_locales/cs/messages.json
Labels: translations

#1974 Add postimees.ee-related domains to MDFP
  src/js/multiDomainFirstParties.js
Labels: MDFP, mystery

#1958 Add TripAdvisor country code domains to MDFP list
  src/js/multiDomainFirstParties.js
Labels: MDFP

#1968 Add greenhouse.io to yellowlist
  src/data/yellowlist.txt
Labels: yellowlist

#1976 Add two MailChimp domains to the yellowlist
  src/data/yellowlist.txt
Labels: yellowlist

#1961 Add News Corp Australia to MDFP list
  src/js/multiDomainFirstParties.js
Labels: MDFP

#1983 Improved Dutch localization
  src/_locales/nl/messages.json
Labels: translations

#1992 Add a couple of domains to NYPR's MDFP list
  src/js/multiDomainFirstParties.js
Labels: MDFP
