Repository EFForg/privacybadger, pull requests merged in 2018-02, with the labels that each got.

#1862 Update Bulgarian translation
  src/_locales/bg/messages.json
Labels: translations

#1879 Add textalk.se to yellowlist
  src/data/yellowlist.txt
Labels: yellowlist

#1881 Add kxcdn.com to yellowlist
  src/data/yellowlist.txt
Labels: yellowlist

#1890 Add bazaarvoice.com to yellowlist
  src/data/yellowlist.txt
Labels: yellowlist

#1885 Add Getty Images to MDFP list
  src/js/multiDomainFirstParties.js
Labels: MDFP

#1884 Add more ESPN domains to MDFP
  src/js/multiDomainFirstParties.js
Labels: MDFP

#1883 Add two more Walmart domains to MDFP list
  src/js/multiDomainFirstParties.js
Labels: MDFP, mystery

#1882 Add Newegg to MDFP list
  src/js/multiDomainFirstParties.js
Labels: MDFP, mystery

#1880 Add Slickdeals to MDFP list
  src/js/multiDomainFirstParties.js
Labels: MDFP, mystery

#1894 Retry on timeout errors when loading a URL
  tests/selenium/pbtest.py
Labels: tests

#1895 Add Cloudinary (CDN) to yellowlist
  src/data/yellowlist.txt
Labels: yellowlist
