Repository EFForg/privacybadger, pull requests merged in 2018-08, with the labels that each got.

#2119 Avoid replacing scripts for SoundCloud widgets
  src/js/contentscripts/socialwidgets.js
Labels: widgets

#2128 Add some missing eBay country codes to MDFP list
  src/js/multiDomainFirstParties.js
Labels: MDFP

#2126 Update Gap's MDFP list
  src/js/multiDomainFirstParties.js
Labels: MDFP

#2127 Add Avito to MDFP list
  src/js/multiDomainFirstParties.js
Labels: MDFP

#2120 Add dropboxusercontent.com to Dropbox's MDFP list
  src/js/multiDomainFirstParties.js
Labels: MDFP

#2124 Add wetter.com to MDFP list
  src/js/multiDomainFirstParties.js
Labels: MDFP

#2121 Add Nintendo domains to MDFP list
  src/js/multiDomainFirstParties.js
Labels: MDFP

#2117 Add zendesk.com to yellowlist
  src/data/yellowlist.txt
Labels: yellowlist

#2132 Add OVH domains to MDFP list
  src/js/multiDomainFirstParties.js
Labels: MDFP

#2122 Add Reuters domains to MDFP list
  src/js/multiDomainFirstParties.js
Labels: MDFP

#2133 Add plot.ly to yellowlist
  src/data/yellowlist.txt
Labels: yellowlist

#2125 Add Expedia Group domains to MDFP list
  src/js/multiDomainFirstParties.js
Labels: MDFP

#2135 Add img.purch.com to yellowlist
  src/data/yellowlist.txt
Labels: yellowlist

#2139 Add Enterprise Holdings domains to MDFP list
  src/js/multiDomainFirstParties.js
Labels: MDFP

#2141 Add Springer Nature domains to MDFP list
  src/js/multiDomainFirstParties.js
Labels: MDFP

#2145 Add an explanation of what happens on data import
  src/_locales/en_US/messages.json
  src/skin/options-layout.css
  src/skin/options.html
Labels: translations
