Repository EFForg/privacybadger, pull requests merged in 2018-11, with the labels that each got.

#2216 Add Spotify domains to MDFP list
  src/js/multiDomainFirstParties.js
Labels: MDFP

#2217 Add bungie.net to yellowlist
  src/data/yellowlist.txt
Labels: yellowlist

#2220 Add yandex.com to the Yandex MDFP
  src/js/multiDomainFirstParties.js
Labels: MDFP

#2183 Add BBC domains to MDFP list
  src/js/multiDomainFirstParties.js
Labels: MDFP

#2230 Add Slashdot and SourceForge to MDFP list
  src/js/multiDomainFirstParties.js
Labels: MDFP

#2222 Add MTV Oy and C More domains to MDFP
  src/js/multiDomainFirstParties.js
Labels: MDFP

#2223 Add squareup.com to yellowlist
  src/data/yellowlist.txt
Labels: yellowlist

#2225 Add Grupa WP domains to MDFP list
  src/js/multiDomainFirstParties.js
Labels: MDFP, mystery

#2226 Update MDFP list for NBC News
  src/js/multiDomainFirstParties.js
Labels: MDFP, mystery

#2227 Add Toyota domains to MDFP list
  src/js/multiDomainFirstParties.js
Labels: MDFP

#2229 Add Pinterest domains to MDFP list
  src/js/multiDomainFirstParties.js
Labels: MDFP
