Repository EFForg/privacybadger, pull requests merged in 2019-10, with the labels that each got.

#2473 Add a few Dynamic Yield domains to the yellowlist
  src/data/yellowlist.txt
Labels: yellowlist

#2476 Fix Google search result image/video thumbnails
  src/js/firstparties/google-search.js
  src/js/firstparties/google-static.js
Labels: first-party

#2479 Remove "sliders let you control" text
  src/_locales/en_US/messages.json
  tests/selenium/options_test.py
Labels: translations

#2461 Add UI for disabling widget replacement for particular widgets
  LICENSE
  src/_locales/en_US/messages.json
  src/js/background.js
  src/js/options.js
  src/js/webrequest.js
  src/lib/i18n.js
  src/lib/vendor/select2-4.0.11/select2-4.0.11.css
  src/lib/vendor/select2-4.0.11/select2-4.0.11.js
  src/skin/options-layout.css
  src/skin/options.html
Labels: translations, ui, widgets

#2481 Add Riot Games domains
  src/js/multiDomainFirstParties.js
Labels: MDFP

#2485 Added The Vanguard Group domains to MDFP
  src/js/multiDomainFirstParties.js
Labels: MDFP

#2280 Add replacement widget for YouTube
  src/data/socialwidgets.json
Labels: widgets
