Repository EFForg/privacybadger, pull requests merged in 2019-09, with the labels that each got.

#2455 Add Bilibili domains to MDFP list
  src/js/multiDomainFirstParties.js
Labels: MDFP

#2445 Testing docs
  doc/tests.md
Labels: documentation & specs

#2456 added schautv.at to "apa.at"
  src/js/multiDomainFirstParties.js
Labels: MDFP

#2457 Add gigya.com to yellowlist
  src/data/surrogates.js
  src/data/yellowlist.txt
Labels: yellowlist
