Repository EFForg/privacybadger, pull requests merged in 2019-11, with the labels that each got.

#2492 Add Korean translation
  src/_locales/ko/messages.json
Labels: translations

#2496 Add KAYAK domains to MDFP
  src/js/multiDomainFirstParties.js
Labels: MDFP

#2501 Fix Messenger photos in non-English locales
  src/js/firstparties/facebook.js
Labels: first-party

#2511 update src/_locales/ko/messages.json
  src/_locales/ko/messages.json
Labels: translations
