Repository EFForg/privacybadger, pull requests merged in 2019-01, with the labels that each got.

#2250 Update Spotify domain list
  src/js/multiDomainFirstParties.js
Labels: MDFP

#2252 Add MyHeritage domains to MDFP list
  src/js/multiDomainFirstParties.js
Labels: MDFP

#2269 Updating Czech (cs_CZ) translation
  src/_locales/cs/messages.json
Labels: translations

#2244 Add sb subdomain to Comscore surrogate
  src/data/surrogates.js
Labels: surrogates
