Repository EFForg/privacybadger, pull requests merged in 2020-05, with the labels that each got.

#2598 More right-to-left (RTL) locale fixes
  src/lib/i18n.js
  src/skin/popup.css
Labels: translations

#2602 Update MDFP list for Discord
  src/js/multiDomainFirstParties.js
Labels: MDFP

#2601 add alicdn.com to yellowlist
  src/data/yellowlist.txt
Labels: yellowlist

#2512 Add replacement widget for Google reCAPTCHA
  src/data/socialwidgets.json
  src/js/contentscripts/socialwidgets.js
  src/js/socialwidgetloader.js
  src/js/webrequest.js
  tests/selenium/clobbering_test.py
  tests/selenium/dnt_test.py
  tests/selenium/pbtest.py
  tests/selenium/popup_test.py
  tests/selenium/surrogates_test.py
  tests/selenium/widgets_test.py
Labels: widgets

#2603 Add immobilienscout24.de domains to MDFP
  src/js/multiDomainFirstParties.js
Labels: MDFP, yellowlist

#2469 Update Alibaba domains in MDFP (alibabacloud.com)
  src/js/multiDomainFirstParties.js
Labels: MDFP

#2596 add doc for privacy tab descriptions in chrome web store
  doc/permissions.md
Labels: documentation & specs

#2611 Improve message used in widget placeholders
  src/_locales/en_US/messages.json
  src/js/contentscripts/socialwidgets.js
  src/js/webrequest.js
  tests/selenium/widgets_test.py
Labels: translations, widgets

#2615 [MDFP] added domains of austrian channels from prosiebensat1.com
  src/js/multiDomainFirstParties.js
Labels: MDFP
