Repository EFForg/privacybadger, pull requests merged in 2020-09, with the labels that each got.

#2652 update popup images on first download page
  src/skin/firstRun.html
  src/skin/images/catches-sneaky.png
  src/skin/images/catches-trackers.png
  src/skin/images/disable-badger.png
  src/skin/images/disable-pb.png
  src/skin/images/learn-browse.png
  src/skin/images/learns-trackers.png
Labels: ui

#2659 Expose privacy overrides in options
  src/_locales/en_US/messages.json
  src/js/background.js
  src/js/options.js
  src/js/webrequest.js
  src/lib/i18n.js
  src/skin/options-layout.css
  src/skin/options.html
Labels: translations

#2683 Add more JetBrains domains to MDFP list
  src/js/multiDomainFirstParties.js
Labels: MDFP

#2686 Add maponline{0,1,2,3}.bdimg.com to yellowlist
  src/data/yellowlist.txt
Labels: yellowlist

#2689 Add videodelivery.net to yellowlist
  src/data/yellowlist.txt
Labels: yellowlist

#2685 Add Singapore Press Holdings domains to MDFP list
  src/js/multiDomainFirstParties.js
Labels: MDFP
