Repository EFForg/privacybadger, pull requests merged in 2021-01, with the labels that each got.

#2724 Add privacy override to disable network prediction
  doc/permissions.md
  src/_locales/en_US/messages.json
  src/js/background.js
  src/js/options.js
  src/skin/options.html
Labels: translations

#2728 Fix inconsistent button font display
  src/js/contentscripts/socialwidgets.js
  src/skin/popup.css
Labels: ux

#2730 Expose sites exemption list for widget tab in options UI
  src/_locales/en_US/messages.json
  src/js/background.js
  src/js/options.js
  src/js/webrequest.js
  src/lib/i18n.js
  src/skin/options-layout.css
  src/skin/options.html
  tests/selenium/widgets_test.py
Labels: translations, ui, widgets
