Repository EFForg/privacybadger, pull requests merged in 2024-01, with the labels that each got.

#2938 Add images-ext-1.discordapp.net and images-ext-2.discordapp.net
  src/data/yellowlist.txt
Labels: yellowlist

#2935 Add tracking domains filter that hides (most recent) remotely learned domains
  src/_locales/en_US/messages.json
  src/js/background.js
  src/js/constants.js
  src/js/options.js
  src/js/webrequest.js
  src/lib/options.js
  src/skin/options.html
  src/tests/tests/options.js
Labels: ui, translations

#2943 Ignore "unexpected error" storage errors
  src/_locales/en_US/messages.json
  src/js/popup.js
  src/js/storage.js
  src/skin/popup.css
Labels: translations
