Repository EFForg/privacybadger, pull requests merged in 2024-07, with the labels that each got.

#2983 Show Chromium users how to pin extension in toolbar
  src/_locales/en_US/messages.json
  src/icons/close.svg
  src/lib/i18n.js
  src/skin/css/firstRun.css
  src/skin/firstRun.html
  src/skin/images/mastodon.svg
  src/skin/images/pinning-instructions.png
  src/skin/js/firstRun.js
  src/skin/popup.html
Labels: ui, translations

#2991 Disable 'Privacy Sandbox' ad tracking by default
  doc/permissions.md
  src/_locales/en_US/messages.json
  src/js/background.js
  src/skin/options.html
Labels: translations

#2990 Add YouTube-specific message to the error report page
  src/_locales/en_US/messages.json
  src/js/popup.js
  src/skin/popup.css
  src/skin/popup.html
Labels: translations

#2996 Add widget replacement for more Twitch embeds
  src/data/socialwidgets.json
Labels: widgets

#2988 Fix release process for Firefox
  release-utils/firefox-release.sh
  release-utils/make-eff-zip.sh
  release-utils/make-release-zip.sh
  release-utils/make-release.sh
  release-utils/make-signed-xpi.sh
  release-utils/post-firefox-release.sh
  release-utils/post-release.sh
Labels: task, documentation & specs

#2994 Fix replacing some lazy-loaded widgets
  src/data/socialwidgets.json
  src/js/contentscripts/socialwidgets.js
  src/js/contentscripts/utils.js
  src/js/webrequest.js
Labels: widgets

#3002 Add Miraheze/Wikitide to MDFP
  src/js/multiDomainFirstParties.js
Labels: MDFP
